// LLL Algebra — UI strings (EN / JA)
// Passed to LLL_I18N.init() in index.html. Chalky's lines use "a|b|c" for random picks
// (see buddyLine() in index.html); {name} placeholders are filled in at runtime.

const STRINGS = {
  en: {
    brand: "LLL Algebra",
    gameTitle: "LLL Algebra",
    scoreLabel: "Score", levelLabel: "Level",
    hintBtn: "Hint (−2 pts)",
    bothSidesLabel: "both sides",
    correctMsg: "Nice — that's the right move.",
    wrongMsg: "Not quite — try again.",
    flipMsg: "Sign flipped: {from} → {to}",
    tierEasy: "Easy", tierMedium: "Medium", tierHard: "Hard",
    topicEquation: "Equations", topicInequality: "Inequalities",
    topicEquationDesc: "Find the value of x",
    topicInequalityDesc: "Find the range of x — watch the sign!",
    topicBrackets: "Brackets",
    topicBracketsDesc: "Expand, then solve for x",
    topicQuadratic: "Quadratics",
    topicQuadraticDesc: "Factorise, then find both answers",
    expandPrompt: "Expand the brackets:",
    factorPrompt: "Factorise:",
    rootsPrompt: "One bracket must be 0, so:",
    rearrangePrompt: "To make one side 0:",
    topicSystem: "Systems",
    topicSystemDesc: "Two equations — find x and y",
    combinePrompt: "To cancel a letter, add or subtract:",
    substitutePrompt: "Substitute back in:",
    scalePrompt: "First, multiply so a letter will cancel:",
    topicFraction: "Fractions",
    topicFractionDesc: "Clear the fractions, then solve for x",
    simplifyPrompt: "Combine the x terms:",
    homeKicker: "Choose a topic", backHome: "Home",
    clearedLabel: "cleared", backLevels: "Levels", lockedLabel: "Locked",
    levelClear: "Level clear!", tierComplete: "{tier} complete!", dailyClear: "Challenge complete!",
    newBest: "New best!", ptsLabel: "pts", streakBonus: "{n} streak bonus",
    nextLevelBtn: "Next level →", levelSelectBtn: "Level select", retryBtn: "Try again", homeBtn: "Home",
    achievementsTitle: "Achievements", achievementsGeneral: "General",
    dailyTitle: "Today's Challenge",
    dailyCompleted: "✓ Completed — come back tomorrow",
    dailyStreakLabel: "day streak",
    reviewTitle: "Mixed Review",
    reviewReady: "{n} questions from all topics",
    reviewBest: "Best {n} pts",
    reviewLocked: "🔒 Clear {n} more levels to unlock",
    reviewComplete: "Review complete!",
    reviewFlawless: "{n} / {total} flawless",
    reviewNudge: "{topic} tripped you up a few times.",
    reviewPractiseBtn: "Practise {topic} →",
    reviewCleanSweep: "Clean sweep!",
    reviewAgainBtn: "Play again",
    introWelcome: "Hi! I'm Chalky. I'll help you learn algebra, one move at a time.",
    introAboutMe: "I'm a piece of chalk from a classroom board. I've written more equations than I can count. My favourite letter? x. Finding it is like solving a mystery!",
    introHowIHelp: "While you play, I'll cheer when you're right, help you bounce back from mistakes, and think it through with you when you tap Hint.",
    introFaceRight: "Right!",
    introFaceOops: "Oops!",
    introFaceHint: "Hint",
    introTopics: "There are 6 topics to master, from Equations all the way to Fractions.",
    introStars: "Solve with no hints and no mistakes to earn ★★★. Clear a level to unlock the next one.",
    introModes: "Come back every day for Today's Challenge, and mix things up with Mixed Review.",
    introReady: "Earn achievements as you go, and tap me on the home screen for tips. Ready?",
    introNextBtn: "Next ▸",
    introStartBtn: "Let's start",
    soundMuteAria: "Mute sound",
    soundUnmuteAria: "Turn sound on",
    tutStartBtn: "Let's go",
    tutGotItBtn: "Got it",
    tutSkipBtn: "Skip",
    tutHelpAria: "How this topic works",
    topicEquationTutBody: "Do the same to both sides. Undo what's around x, one move at a time, until x is on its own.",
    topicEquationTutTip1: "Undo + and − first, then × and ÷",
    topicEquationTutTip2: "Pick the opposite move: + 5 is undone by − 5",
    topicInequalityTutBody: "Solve it just like an equation — but if you × or ÷ by a negative number, the sign flips.",
    topicInequalityTutTip1: "÷ (−3) turns > into <",
    topicInequalityTutTip2: "The answer is a range, like x < 4",
    topicBracketsTutBody: "Expand the brackets first: multiply everything inside by the number outside. Then solve as normal.",
    topicBracketsTutTip1: "2(x + 3) becomes 2x + 6",
    topicBracketsTutTip2: "Multiply both terms inside, not just the first one",
    topicQuadraticTutBody: "Factorise into two brackets. If two things multiply to 0, one of them must be 0, so you get two answers.",
    topicQuadraticTutTip1: "x² + 5x + 6 = (x + 2)(x + 3): the two numbers add to 5 and multiply to 6",
    topicQuadraticTutTip2: "Answers are written smallest first: x = −3, −2",
    topicQuadraticTutTip3: "Not = 0 yet? Move everything to one side first",
    topicSystemTutBody: "Add or subtract the two equations so one letter cancels out. Solve for the other letter, then substitute it back.",
    topicSystemTutTip1: "x + y = 9 and 2x - y = 3: adding them cancels y",
    topicSystemTutTip2: "Found x? Put it back into either equation to find y",
    topicFractionTutBody: "Get rid of the fractions first: multiply both sides by the number on the bottom. With two fractions, use the smallest number both bottoms go into.",
    topicFractionTutTip1: "2x/3 = 8: × 3 gives 2x = 24",
    topicFractionTutTip2: "x/2 + x/3: × 6 clears both fractions at once",
    tipTag: "New in {tier}",
    tipDemoLabel: "Example",
    tipOkBtn: "Got it, let's go",
    chalky3Star: "Perfect! ★★★|Flawless, not a single slip!|Three stars! You made that look easy",
    chalkyFewerStars: "Nice! Try for ★★★ next time|Solved! Can you get ★★★ next time?|You got there! No hints, no slips = ★★★",
    chalkyTierDone: "You finished {tier}! 🎉|{tier} cleared! On to the next one!",
    chalkyTopicMastered: "You mastered {topic}! 🏆",
    chalkyLinesMeet: "That's where the lines meet!",
    graphLine1: "Line 1", graphLine2: "Line 2",
    graphAria: "Graph of both lines crossing at ({x}, {y})",
    chalkyDaily: "Challenge done! See you tomorrow!",
    chalkyDailyStreak: "{n} days in a row! 🔥|{n}-day streak! Keep it going!",
    chalkyReview: "Review done! Practice makes it stick.|Nice mix! Every round helps.",
    chalkyReviewFlawless: "{n} out of {n}, no slips! Amazing!",
    buddyCorrect: "Nice!|That's it!|Good move!|Keep going!",
    buddyWrong: "Almost! Try again|So close!|Not that one — try another|Mistakes help you learn!",
    buddyHint: "Here's a clue!|Let's think…|Hmm, look at this",
    buddySolved: "You did it!|Solved!|Brilliant!",
    buddyDoze: "Zzz… stuck? Try a hint!",
    homeFirst: "Pick a topic to start. Equations is a great first step!",
    homeDaily: "Today's Challenge is ready. One quick problem a day!",
    homeDailyStreak: "Today's Challenge is waiting. Keep your {n}-day streak going! 🔥",
    homeReviewSoon: "Just {n} more levels and Mixed Review unlocks!",
    homeAlmostTier: "Only {n} more to finish {topic} · {tier}!",
    homeTryTopic: "Ready for something new? Give {topic} a try!",
    homeCheer: "Every mistake is practice. Keep going!|Little steps add up. You've got this!|Algebra is just balancing, and you're good at it!|One more level? I believe in you!|Tap a topic and let's solve something!",
    homeTapHint: "Tap me!"
  },
  ja: {
    brand: "LLL 代数",
    gameTitle: "LLL 代数",
    scoreLabel: "スコア", levelLabel: "レベル",
    hintBtn: "ヒント (−2 pt)",
    bothSidesLabel: "両辺で" ,
    correctMsg: "正解です！",
    wrongMsg: "違います、もう一度。",
    flipMsg: "不等号の向きが逆に：{from} → {to}",
    tierEasy: "やさしい", tierMedium: "ふつう", tierHard: "むずかしい",
    topicEquation: "方程式", topicInequality: "不等式",
    topicEquationDesc: "xの値を求めよう",
    topicInequalityDesc: "xの範囲を求めよう — 不等号の向きに注意！",
    topicBrackets: "かっこ",
    topicBracketsDesc: "かっこを展開してxを求めよう",
    topicQuadratic: "二次方程式",
    topicQuadraticDesc: "因数分解して2つの解を求めよう",
    expandPrompt: "かっこを展開すると：",
    factorPrompt: "因数分解すると：",
    rootsPrompt: "どちらかのかっこが0なので：",
    rearrangePrompt: "右辺を0にするには：",
    topicSystem: "連立方程式",
    topicSystemDesc: "2つの式からxとyを求めよう",
    combinePrompt: "文字を1つ消すには、足すか引くか：",
    substitutePrompt: "代入すると：",
    scalePrompt: "まず、文字が消えるようにかけると：",
    topicFraction: "分数",
    topicFractionDesc: "分数をなくしてxを求めよう",
    simplifyPrompt: "xの項をまとめると：",
    homeKicker: "トピックを選ぼう", backHome: "ホーム",
    clearedLabel: "クリア", backLevels: "レベル選択", lockedLabel: "ロック中",
    levelClear: "クリア！", tierComplete: "{tier} コンプリート！", dailyClear: "チャレンジ達成！",
    newBest: "ベスト更新！", ptsLabel: "pt", streakBonus: "{n}連続ボーナス",
    nextLevelBtn: "次のレベル →", levelSelectBtn: "レベル選択", retryBtn: "もう一度", homeBtn: "ホーム",
    achievementsTitle: "実績", achievementsGeneral: "全般",
    dailyTitle: "今日のチャレンジ",
    dailyCompleted: "✓ 完了 — また明日",
    dailyStreakLabel: "日連続",
    reviewTitle: "ミックス復習",
    reviewReady: "全トピックから{n}問",
    reviewBest: "ベスト {n} pt",
    reviewLocked: "🔒 あと{n}レベルクリアで解放",
    reviewComplete: "復習完了！",
    reviewFlawless: "ノーミス {n} / {total}",
    reviewNudge: "{topic}で何度かつまずきました。",
    reviewPractiseBtn: "{topic}を練習 →",
    reviewCleanSweep: "パーフェクト！",
    reviewAgainBtn: "もう一度",
    introWelcome: "やあ！チョークのチョーキーだよ。代数を1歩ずつ一緒に学ぼう！",
    introAboutMe: "ぼくは教室の黒板のチョーク。式をたくさん書いてきたよ。好きな文字はx！見つけるのはなぞ解きみたいでワクワクするんだ。",
    introHowIHelp: "プレイ中は、正解したら一緒に喜んで、まちがえたら励まして、ヒントを押したら一緒に考えるよ。",
    introFaceRight: "正解！",
    introFaceOops: "おしい！",
    introFaceHint: "ヒント",
    introTopics: "トピックは全部で6つ。方程式から分数までマスターしよう！",
    introStars: "ヒントなし・ミスなしで★3つ！レベルをクリアすると次のレベルが解放されるよ。",
    introModes: "毎日の「今日のチャレンジ」と、全トピックから出る「ミックス復習」もあるよ。",
    introReady: "実績も集めてね。ホームでぼくをタップするとヒントがもらえるよ。準備はいい？",
    introNextBtn: "次へ ▸",
    introStartBtn: "はじめる",
    soundMuteAria: "サウンドをオフ",
    soundUnmuteAria: "サウンドをオン",
    tutStartBtn: "はじめる",
    tutGotItBtn: "OK",
    tutSkipBtn: "スキップ",
    tutHelpAria: "このトピックの解き方",
    topicEquationTutBody: "両辺に同じ操作をしよう。xのまわりにあるものを1つずつ取り除いて、xだけを残します。",
    topicEquationTutTip1: "まず＋と−を消して、次に×と÷",
    topicEquationTutTip2: "反対の操作を選ぼう：+ 5 は − 5 で消せます",
    topicInequalityTutBody: "方程式と同じように解きます。ただし、負の数でかけたり割ったりすると、不等号の向きが逆になります。",
    topicInequalityTutTip1: "÷ (−3) で > は < に変わります",
    topicInequalityTutTip2: "答えは x < 4 のような範囲になります",
    topicBracketsTutBody: "まずかっこを展開します。かっこの外の数を、中のすべての項にかけましょう。そのあとはいつも通りに解きます。",
    topicBracketsTutTip1: "2(x + 3) は 2x + 6 になります",
    topicBracketsTutTip2: "最初の項だけでなく、中の両方の項にかけよう",
    topicQuadraticTutBody: "2つのかっこに因数分解します。かけて0になるなら、どちらかが0なので、答えは2つになります。",
    topicQuadraticTutTip1: "x² + 5x + 6 = (x + 2)(x + 3)：足して5、かけて6になる2つの数",
    topicQuadraticTutTip2: "答えは小さい順に書きます：x = −3, −2",
    topicQuadraticTutTip3: "右辺が0でないときは、まず全部を左辺に移そう",
    topicSystemTutBody: "2つの式を足すか引いて、文字を1つ消します。残った文字を求めたら、それを代入してもう1つを求めます。",
    topicSystemTutTip1: "x + y = 9 と 2x - y = 3 を足すと y が消えます",
    topicSystemTutTip2: "xが分かったら、どちらかの式に代入してyを求めよう",
    topicFractionTutBody: "まず分数をなくそう。両辺に分母の数をかけます。分数が2つなら、どちらの分母でも割り切れる一番小さい数をかけます。",
    topicFractionTutTip1: "2x/3 = 8：3をかけると 2x = 24",
    topicFractionTutTip2: "x/2 + x/3：6をかけると分数が両方消えます",
    tipTag: "「{tier}」の新しいポイント",
    tipDemoLabel: "例",
    tipOkBtn: "OK、やってみる！",
    chalky3Star: "パーフェクト！★★★|ノーミス！すごい！|★3つ！かんたんそうだったね",
    chalkyFewerStars: "いいね！次は★3つをねらおう|クリア！次は★★★いけるかな？|できたね！ヒントなし・ミスなしで★★★だよ",
    chalkyTierDone: "「{tier}」クリア！🎉|「{tier}」を全部クリア！次へ行こう！",
    chalkyTopicMastered: "{topic}をマスターしたね！🏆",
    chalkyLinesMeet: "ここで2本の線が交わるよ！",
    graphLine1: "式1", graphLine2: "式2",
    graphAria: "2本の直線が ({x}, {y}) で交わるグラフ",
    chalkyDaily: "チャレンジ達成！また明日ね！",
    chalkyDailyStreak: "{n}日連続！🔥|{n}日連続！この調子！",
    chalkyReview: "復習おつかれさま！くり返すと身につくよ。|いいミックス！毎回力になるよ。",
    chalkyReviewFlawless: "{n}問中{n}問ノーミス！すごい！",
    buddyCorrect: "いいね！|その通り！|ナイス！|その調子！",
    buddyWrong: "おしい！もう一度|あと少し！|それじゃないよ、別のを選ぼう|まちがいも勉強のうち！",
    buddyHint: "ヒントだよ！|考えてみよう…|ここを見てみて",
    buddySolved: "できた！|正解！|すごい！",
    buddyDoze: "Zzz… 迷ったらヒントを使ってみよう！",
    homeFirst: "トピックを選んで始めよう！まずは方程式がおすすめだよ。",
    homeDaily: "今日のチャレンジが待ってるよ。1日1問、サクッと解こう！",
    homeDailyStreak: "今日のチャレンジが待ってるよ。{n}日連続を続けよう！🔥",
    homeReviewSoon: "あと{n}レベルクリアでミックス復習が解放されるよ！",
    homeAlmostTier: "{topic}・{tier}はあと{n}問でクリア！",
    homeTryTopic: "新しいことに挑戦してみる？{topic}をやってみよう！",
    homeCheer: "まちがいも練習のうち。その調子！|小さな一歩が力になるよ。|代数はバランス。きみなら大丈夫！|もう1レベルやってみない？|トピックを選んで、一緒に解こう！",
    homeTapHint: "タップしてね！"
  }
};

export { STRINGS };